### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by freegheist** [hrishioa/rakis#2]
cool project... but the non-commercial license I think is potentially going to cause issues or trip-up any actual crypto uptake.

i.e. any kind of use within a crypto thats paid by that crypto (or e.g. incentivizing the devs using blockchain funds themselves) could be argued to be commercial use (given that cryptos themselves are a form of money) and make this not usable, no?

why not MIT which is the norm for crypto projects?

**Comment by hrishioa** [comment]
Good point. Rakis to me is still inside the stability test regime. While the ideas are useful (and openly available), the code itself shouldn't ideally be used directly. I'm happy for projects to open a line of comms with me or Julian about using the code, and to grant a license gratis based on a conversation.

If/when the Rakis code is more stable we'll have an internal discussion on license changes.

Closing this for now since the license was intentional, but happy to continue the discussion!
